import Head from "next/head";
import Clock from "../components/Clock";
import Spotify from "@/components/Spotify";
import Pomodoro from "@/components/Pomodoro";
import WaterReminder from "@/components/WaterReminder";

export default function Home() {
    return (
        <>
            <Head>
                <title>Zen</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="background">
                <div className="breath-sphere"></div>
                <Clock />
                {/*<Spotify />*/}
                <Pomodoro />
                <WaterReminder />
            </div>
        </>
    );
}
